"""Generate the MindMate final presentation (PPTX).

Produces ``docs/presentation/MindMate_Final_Presentation.pptx``, a 16:9 deck
summarising the project for the viva. Figures generated by ``make_figures``
and ``make_diagrams`` are embedded directly.

Usage::

    python -m scripts.build_slides
"""
from __future__ import annotations

from pathlib import Path

from pptx import Presentation
from pptx.dml.color import RGBColor
from pptx.enum.text import MSO_ANCHOR, PP_ALIGN
from pptx.util import Emu, Inches, Pt

ROOT = Path(__file__).resolve().parent.parent
FIG = ROOT / "docs" / "figures"
OUT = ROOT / "docs" / "presentation" / "MindMate_Final_Presentation.pptx"
OUT.parent.mkdir(parents=True, exist_ok=True)

NAVY = RGBColor(0x1F, 0x3B, 0x63)
GREEN = RGBColor(0x2C, 0x6E, 0x49)
GREY = RGBColor(0x55, 0x55, 0x55)
LIGHT = RGBColor(0xEE, 0xF2, 0xF7)
WHITE = RGBColor(0xFF, 0xFF, 0xFF)

SW, SH = Inches(13.333), Inches(7.5)

prs = Presentation()
prs.slide_width = SW
prs.slide_height = SH
BLANK = prs.slide_layouts[6]


def _bg(slide, color=WHITE):
    slide.background.fill.solid()
    slide.background.fill.fore_color.rgb = color


def _box(slide, left, top, width, height):
    tb = slide.shapes.add_textbox(left, top, width, height)
    tb.text_frame.word_wrap = True
    return tb


def _set(p, text, size, color=NAVY, bold=False, align=PP_ALIGN.LEFT, italic=False):
    p.text = text
    p.alignment = align
    for r in p.runs:
        r.font.size = Pt(size)
        r.font.bold = bold
        r.font.italic = italic
        r.font.color.rgb = color
        r.font.name = "Calibri"


def _bar(slide):
    """Accent side bar + footer."""
    shp = slide.shapes.add_shape(1, 0, 0, Inches(0.18), SH)
    shp.fill.solid()
    shp.fill.fore_color.rgb = GREEN
    shp.line.fill.background()
    foot = _box(slide, Inches(0.4), Inches(7.0), Inches(12.5), Inches(0.4))
    _set(foot.text_frame.paragraphs[0],
         "MindMate, An AI-Powered Mental Health Assistant for Students",
         10, GREY, italic=True)


def title_slide():
    s = prs.slides.add_slide(BLANK)
    _bg(s, NAVY)
    t = _box(s, Inches(1), Inches(2.1), Inches(11.3), Inches(1.5))
    _set(t.text_frame.paragraphs[0], "MindMate", 60, WHITE, bold=True, align=PP_ALIGN.CENTER)
    sub = _box(s, Inches(1), Inches(3.5), Inches(11.3), Inches(0.8))
    _set(sub.text_frame.paragraphs[0],
         "An AI-Powered Mental Health Assistant for Students",
         26, RGBColor(0x9E, 0xC4, 0xA8), italic=True, align=PP_ALIGN.CENTER)
    meta = _box(s, Inches(1), Inches(4.8), Inches(11.3), Inches(2))
    tf = meta.text_frame
    lines = [
        ("M.Sc. (Data Science), Final Project Report", 18, WHITE, True),
        ("Submitted by: Ganesh L   |   Enrolment No: O24MSD110165", 15, LIGHT, False),
        ("Guide: Mr. Prashant Stephens   |   In association with Plag Pro, Noida", 15, LIGHT, False),
        ("Chandigarh University · 2026", 15, LIGHT, False),
    ]
    for i, (txt, sz, col, bold) in enumerate(lines):
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        _set(p, txt, sz, col, bold=bold, align=PP_ALIGN.CENTER)
        p.space_after = Pt(8)


def content_slide(title, bullets, subtitle=None):
    s = prs.slides.add_slide(BLANK)
    _bg(s)
    _bar(s)
    t = _box(s, Inches(0.5), Inches(0.35), Inches(12.3), Inches(0.9))
    _set(t.text_frame.paragraphs[0], title, 32, NAVY, bold=True)
    top = Inches(1.5)
    if subtitle:
        st = _box(s, Inches(0.55), Inches(1.35), Inches(12), Inches(0.5))
        _set(st.text_frame.paragraphs[0], subtitle, 16, GREEN, italic=True)
        top = Inches(2.0)
    body = _box(s, Inches(0.6), top, Inches(12.1), Inches(4.8))
    tf = body.text_frame
    for i, b in enumerate(bullets):
        level = 0
        text = b
        if isinstance(b, tuple):
            level, text = b
        p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
        bullet_char = "▸ " if level == 0 else "- "
        _set(p, bullet_char + text, 20 if level == 0 else 17,
             NAVY if level == 0 else GREY, bold=(level == 0))
        p.level = level
        p.space_after = Pt(10 if level == 0 else 5)
    return s


def image_slide(title, image_name, caption=None, bullets=None):
    s = prs.slides.add_slide(BLANK)
    _bg(s)
    _bar(s)
    t = _box(s, Inches(0.5), Inches(0.35), Inches(12.3), Inches(0.9))
    _set(t.text_frame.paragraphs[0], title, 32, NAVY, bold=True)

    img = FIG / image_name
    if bullets:
        # image left, bullets right
        if img.exists():
            s.shapes.add_picture(str(img), Inches(0.5), Inches(1.6),
                                 height=Inches(4.8))
        body = _box(s, Inches(7.2), Inches(1.8), Inches(5.6), Inches(4.8))
        tf = body.text_frame
        for i, b in enumerate(bullets):
            p = tf.paragraphs[0] if i == 0 else tf.add_paragraph()
            _set(p, "▸ " + b, 17, NAVY, bold=True)
            p.space_after = Pt(10)
    else:
        if img.exists():
            pic = s.shapes.add_picture(str(img), Inches(2.5), Inches(1.5),
                                       height=Inches(5.0))
        if caption:
            cap = _box(s, Inches(0.6), Inches(6.5), Inches(12), Inches(0.4))
            _set(cap.text_frame.paragraphs[0], caption, 13, GREY,
                 italic=True, align=PP_ALIGN.CENTER)
    return s


def section_divider(title, n):
    s = prs.slides.add_slide(BLANK)
    _bg(s, NAVY)
    num = _box(s, Inches(1), Inches(2.6), Inches(11.3), Inches(1))
    _set(num.text_frame.paragraphs[0], f"{n:02d}", 40, RGBColor(0x9E, 0xC4, 0xA8),
         bold=True, align=PP_ALIGN.CENTER)
    t = _box(s, Inches(1), Inches(3.6), Inches(11.3), Inches(1.2))
    _set(t.text_frame.paragraphs[0], title, 40, WHITE, bold=True, align=PP_ALIGN.CENTER)


def build():
    # 1. Title
    title_slide()

    # 2. Problem & Motivation
    content_slide("The Problem", [
        "Student mental-health needs are rising, but counselling capacity is limited (WHO, 2022; Auerbach et al., 2018).",
        "Stigma, cost and waiting times stop many students from seeking help early.",
        "Generic apps rarely personalise support or handle crises transparently.",
        ("There is a need for accessible, stigma-free, personalised first-line support, clearly distinct from clinical care."),
    ], subtitle="Why MindMate?")

    # 3. Objectives
    content_slide("Project Objectives", [
        "Design and develop an AI mental-health assistant for students.",
        "Personalise its support using machine-learning algorithms.",
        "Evaluate its effectiveness on mental-health and academic outcomes.",
    ], subtitle="Three core objectives")

    # 4. Solution overview
    content_slide("MindMate, Solution Overview", [
        "A privacy-respecting Streamlit web app with six pages: Home, Chat, Mood Tracker, Self-Check, Insights, Resources.",
        "Empathetic conversational assistant (OpenAI API with a robust offline fallback engine).",
        "ML personalisation: sentiment analysis, student segmentation, stress prediction, transparent recommendations.",
        "Safety-first: every message screened for crisis signals before any reply.",
        "PHQ-9 and GAD-7 self-checks with validated severity bands.",
    ], subtitle="What we built")

    # 5. Architecture (image)
    image_slide("System Architecture", "diagram_architecture.png", bullets=[
        "Presentation layer (Streamlit)",
        "Service layer orchestrates logic",
        "Assistant + ML domain layer",
        "Local SQLite persistence",
        "OpenAI API is optional",
    ])

    # 6. Tech stack
    content_slide("Technology Stack", [
        "Language & UI: Python 3.12, Streamlit (multipage).",
        "Machine learning: scikit-learn (K-Means, Logistic Regression, PCA), VADER for sentiment.",
        "LLM: OpenAI Chat Completions API, with an offline rule-based engine for zero-dependency demos.",
        "Data & analysis: pandas, numpy, scipy; visualisation with plotly and matplotlib.",
        "Persistence: SQLite; models serialised with joblib; tested with pytest (34 tests).",
    ], subtitle="Open-source and reproducible")

    # 7. Personalisation divider
    section_divider("Machine-Learning Personalisation", 1)

    # 8. Segmentation
    image_slide("Student Segmentation (K-Means)", "fig_segment_pca.png", bullets=[
        "Four support segments: Thriving, Coping, At-Risk, High-Need",
        "Six wellbeing features",
        "Silhouette score 0.209",
        "Labels ranked by a wellbeing index",
        "Each segment maps to a tailored plan",
    ])

    # 9. Stress classifier
    image_slide("Stress Classification", "fig_confusion_matrix.png", bullets=[
        "Logistic Regression (Low/Moderate/High)",
        "Test accuracy: 90.0%",
        "Macro-F1: 0.889",
        "Feeds the dashboard + recommender",
        "Transparent probability output",
    ])

    # 10. Safety
    content_slide("Safety-First Design", [
        "Every user message is screened for crisis signals BEFORE a reply is generated.",
        "Three risk levels: none, elevated, crisis.",
        "Crisis triggers a calm, validating message + 24x7 helplines (Tele-MANAS, Vandrevala, AASRA, iCall).",
        "Conservative by design: a false positive is far less costly than a missed crisis.",
        "MindMate never diagnoses and always defers clinical concerns to professionals.",
    ], subtitle="Ethics and user safety")

    # 11. Evaluation divider
    section_divider("Evaluation of Effectiveness", 2)

    # 12. Evaluation results
    image_slide("Pilot Evaluation Results", "fig_evaluation_prepost.png",
                caption="Simulated 4-week pilot (120 treatment vs 120 control). "
                        "Synthetic data, demonstrates the evaluation methodology.")

    # 13. Effect sizes
    image_slide("Effect Sizes", "fig_effect_sizes.png", bullets=[
        "PHQ-9: d = 1.62 (large)",
        "GAD-7: d = 1.47 (large)",
        "Wellbeing: d = 1.85 (large)",
        "Focus hours: d = 1.44 (large)",
        "All p < 0.001 (synthetic data)",
    ])

    # 14. Testing
    content_slide("Testing & Validation", [
        "34 automated pytest tests, unit, integration and system levels, all passing.",
        "Dedicated safety-critical tests (crisis detection, no over-flagging of phrases like 'killing it in exams').",
        "Models validated on a stratified hold-out: accuracy 0.900, macro-F1 0.889; clustering silhouette 0.209.",
        "Reproducible end-to-end via a fixed random seed.",
    ], subtitle="Quality assurance")

    # 15. Conclusion
    content_slide("Conclusion & Future Scope", [
        "All three objectives met: a working assistant, ML personalisation, and a reproducible evaluation.",
        ("Contributions: transparent ML personalisation, safety-first + offline-capable design, reproducible evaluation pipeline."),
        "Future: IRB-approved real user study; multilingual support (Hindi & regional languages); mobile app.",
        "Future: transformer-based emotion models; campus-counselling referral integration; secure cloud deployment.",
    ], subtitle="Outcomes and next steps")

    # 16. Thank you
    s = prs.slides.add_slide(BLANK)
    _bg(s, NAVY)
    t = _box(s, Inches(1), Inches(2.7), Inches(11.3), Inches(1.2))
    _set(t.text_frame.paragraphs[0], "Thank You", 54, WHITE, bold=True, align=PP_ALIGN.CENTER)
    sub = _box(s, Inches(1), Inches(4.0), Inches(11.3), Inches(1.2))
    tf = sub.text_frame
    _set(tf.paragraphs[0], "Questions & Discussion", 24,
         RGBColor(0x9E, 0xC4, 0xA8), italic=True, align=PP_ALIGN.CENTER)
    p2 = tf.add_paragraph()
    _set(p2, "Project repository: github.com/gannyprodigy/mindmate-mental-health-assistant",
         16, LIGHT, align=PP_ALIGN.CENTER)

    prs.save(str(OUT))
    print(f"Presentation written to {OUT}")
    print(f"Slides: {len(prs.slides._sldIdLst)}  |  Size: {OUT.stat().st_size/1024:.0f} KB")


if __name__ == "__main__":
    build()
